### ISSUE TITLE
[dregora - question] Will I have to restart when Dregora is out of beta?

### ISSUE THREAD

**Issue by StefanArmand** [NLBlackEagle/Dregora#10]
Thank you for the mod, it looks amazing! I want to start playing right away, but I wouldn't want to restart later. Will I be forced to do it when its out of beta?

**Comment by SamB440** [comment]
Hi, old chunks will not be affected when Dregora is updated. Only new chunks will be.

**Comment by StefanArmand** [comment]
So its better to wait so that all the chunks get updated, got it.

**Comment by NLBlackEagle** [comment]
Good question, and no you will not be forced to restart the whole map however restarting will mean new functions, updates and so on. As I do not have a development roadmap yet I'll shortly explain what beta actually means for dregora:

The map is 24k x 24k blocks, the middle continent "Rainforest" is nearly finished ( See it as a biome group ) The outter layers are still from a very old build so ugly & buggy for my standards. During the beta I will however focus 90% of my attention on rainforest which include the following to do's:

- 8 more denizen compatible Dungeons
- one or two tribal villages
- Subtropical Pirate theme expansion
- Ocean Update

After this the beta will be at a end and I will start expanding / redesigning biomes more towards the outer edges.

Important Note: I am creating a script/plugin/mod that saves player structures, deletes the map, update the chunks & puts all player placed items back into the map. This means you can update without losing player progression :) This will be released under the Dregora Addon and probably will be for cauldron/spigot use only ( Maayybee forge )

**Comment by StefanArmand** [comment]
Thank you for the reply! You have a lot planned for the beta, awesome 👍 

That Addon sounds very useful, and I really hope you release it for Forge since that's what I use, if not, no matter, I will try to learn to use Cauldron/Spigot. Do you have an estimate for when you think you might release a first working version? And will it work with the beta save we have right now?

**Comment by SamB440** [comment]
Hi, sorry for the late reply... there has been a lot going on recently for both I and NLBlackEagle.

As far as I am aware, Dregora works with forge. All new versions will work fine with older saves (at least they should!), but as I said old chunks won't be affected.

Closed. If you have other questions feel free to ask.
