### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by VioletWyvern** [NLBlackEagle/Dregora#11]
This is a good world generate mod,  Unique biome design,  Lots of spacial terrain...
But I have encounter some minor bugs : 

1. Some custom structures are generate weirdly, Sometimes you will encounter an "Half Breaking Windmill" or "A house above small pond with no floor"...

2. The redstone mechanism in the dungeons are absolutely not working,  All pressure pads (except for  opening a single iron door) and piston doors were completely not working,  This would make players cannot completely finished the entire dungeon... 

3. All treasure chests were completely empty,  You cannot find any valuable loots in the chests,  This makes player feels no need to exploring dungeons since there's no treasures....

**Comment by SamB440** [comment]
Hi,

1. Recently Dregora changed from TC to OTG so there are bugs like this.

2. This requires the denizen addon I believe.

3. This definitely requires the denizen addon.

Denizen addon is currently not available but will be soon after other bugs are fixed. It may also cost money - however that is up to NLBlackEagle.

**Comment by NLBlackEagle** [comment]
@SamB440 Thanks for the help on this issue :+1: 

@VioletWyvern 
Thank you very much for posting these issues, Im currently drowining in the amount of work I have for the upcoming exams, internship and double that amount of work for other projects. These are now noted in the upcoming roadmap ( Fancy to do list ) which you can find here: https://roadmap.dregora.com/?controller=BoardViewController&action=readonly&token=faa613072bf23a92431a5afa615629caea1082bea725c7ba232bfec868fd or at https://dregora.com/download#panel-53-2-0-0

**Comment by NLBlackEagle** [comment]
Fixed Empty Chests ( V1.2 ) & Weird structure placement. ( V1.3 )
Dungeon 01 should definitely work correctly now( V1.2 ) Dungeon 02 will be completely re-done and re-uploaded to Dregora V1.3 or V1.2

V 1.3 is to be released upcoming 13th

**Comment by SamB440** [comment]
Fixed a while back.
