### ISSUE TITLE
Items not spawning in dungeon chests

### ISSUE THREAD

**Issue by Barerock** [NLBlackEagle/Dregora#14]
I am not seeing any loot at all in any Dregora dungeon chests. Really disappointing, pretty simple, how do I fix it.

Also I don't know how to label this. Can't click anything that looks like it would work, sorry if I'm doing it wrong.

**Comment by SamB440** [comment]
Hi, I've had to close this as this is not an issue.

Dregora does not currently offer loot in chests. We've been working on fixing the bugs within Dregora currently, as we recently transferred from TC to OTG. 

Soon the Denizen addon for Dregora will be available - this will add loot in chests. However, this may or may not cost money, as it will add other things among loot in chests - you'll have to ask NLBlackEagle, but I'm not sure if even he knows.

Dregora has been a project that NLBlackEagle has been working on for years, and it takes time to add things like this.

Thanks.
