### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by Crush303** [NLBlackEagle/Dregora#15]
I am not quite sure if this is a known bug and i just didn't see it but this mod, for some reason, seems to not work with the Conquest resource pack. I had issues when I was using this mod and switched over to using the Conquest resource pack [found here](https://www.planetminecraft.com/texture_pack/conquest-32x32/l) mid-game. My game crashed, then when i loaded back into it, there was a big wall of normal minecraft terrain in front of me. I flew around a bit and found out the rest of the world was being generated as a normal minecraft world.

Just to be sure, I made a new world using only the resource pack, this mod, and the mods that are necessary for this mod to work and the terrain was normal minecraft terrain. I turned the resource pack off, did it again, and the unique generation worked again and everything was fine. Also, I did the same thing, however generating a world of Skylands [found here](https://minecraft.curseforge.com/projects/open-terrain-generator) and it worked fine with and without the pack loaded.

I find this really weird and honestly, I would not be surprised if the Conquest resource pack did some funky stuff with the terrain somehow, although I'mpretty sure it doesn't, especially because the Skylands generated properly.

The only thing I could think of is that all these mods are very taxing on my computer and slow down and freeze/crash my game as I imagine the world generation you are using is complicated, but that still does not explain why the world generation is just flat out not working when I have this texture pack loaded.

All in all, I have no idea whats going on, it still could be something else that I am doing, as I find this extremely odd, but I am 99% sure it is something going on with the pack.

**Comment by SamB440** [comment]
Texture packs do not affect world generation in any way. This is a server issue.

**Comment by Crush303** [comment]
Yeah, that makes sense, but that still doesn't help my issue, the world generation is still not working

**Comment by SamB440** [comment]
Please provide your bukkit.yml and startup log (/logs/latest.log), and paste a screenshot of your /plugins output, and /ver output.

**Comment by Crush303** [comment]
[latest.log](https://github.com/NLBlackEagle/Dregora/files/2247147/latest.log)
Here is my latest startup log

I don't know how to attain the other things

**Comment by SamB440** [comment]
You need to assign more RAM to Minecraft. Java ran out of available memory when OTG tried to generate the world, causing bugs.

(Error: https://pastebin.com/Uz13qPHF)

**Comment by Crush303** [comment]
Awesome, that did the trick. Thank you!

**Comment by SamB440** [comment]
Glad to hear it. 

Closed.
