### ISSUE TITLE
[Dregora - Suggestion] Deeper Ocean(s)

### ISSUE THREAD

**Issue by Zygus42** [NLBlackEagle/Dregora#19]
* Minecraft version 1.12
* Dregora version 1.51
* Environment Type (Forge or Server such as Spigot) forge-1.12.2-14.23.5.2806-installer-win

Would be nice if the Oceans in general or some part of the Ocean was deeper.  Your water level is higher than vanilla, so would allow for some real deep canyons etc to allow people to build some proper underwater bases.

**Comment by NLBlackEagle** [comment]
This is a Nice suggestion, however I will hold out on it until 1.13 for OTG has been released. This way I Will be able to Cook up a grand ocean update in one go :)

Thanks for the suggestion!

**Comment by NLBlackEagle** [comment]
Added to v1.62 Deeper oceans are now a part of Dregora! Plans are to change even more for 1.63, such as the ocean caverns.
