### ISSUE TITLE
[Dregora - Issue] Player stuck inside structure on spawn

### ISSUE THREAD

**Issue by WrongWeekend** [NLBlackEagle/Dregora#20]
Minecraft Version: 1.12.2

Dregora Version:  Dregora-1.12.2-v1.5.1 HotFix ( NO-LAG Update )
https://minecraft.curseforge.com/projects/dregora/files/2669473

https://i.imgur.com/IGHRgjRl.png
Upon starting an OTG world with the Dregora preset, the player is trapped inside of a structure. Unless the player manages to dig out in time, repeated suffocation damage leads to death.

https://i.imgur.com/CNut27El.png
This is the structure causing the issue. I recall that older versions of Dregora did not have this structure, and the player simply spawned on top of the sand. I assume that the player spawn point was not updated to reflect the addition of the structure.

**Comment by SamB440** [comment]
Are you using Forge or Spigot?

**Comment by WrongWeekend** [comment]
I am using Forge.

**Comment by NLBlackEagle** [comment]
This issue has been a part of Dregora for some time. That said i am confident having collected enough information to fix it for good in the next update which will be released in 2 weeks

**Comment by ProsperCraft** [comment]
Not having this issue in 1.16.5

**Comment by NLBlackEagle** [comment]
Fixed on both 1.12.2 as 1.16 as the structure has been replaced and the player now spawns at 0,0
