### ISSUE TITLE
[Dregora - Issue] Tall beaches?

### ISSUE THREAD

**Issue by craft90** [NLBlackEagle/Dregora#23]
* Minecraft version 1.12.2
* Dregora version v. 1.6.2 Survival+
* Environment Type (Forge or Server such as Spigot) Forge 14.23.5.2847
* Steps to reproduce the problem:
Create a new world
Fly away from the Jungle to x -7094, z 1516 y 102 (went there to take a look at Sapphire City)
Take a look at the beaches...  they are really high. They go from 74 up to 127 like a mountain rage, sharp inclines and a quick tapering off. The issue doesn't seem to just be around Sapphire city but also around Dearoc. The jungles doesn't seem to suffer from these issues as far as I can tell.
![2019-11-27_17 41 35](https://user-images.githubusercontent.com/12762624/69743195-56324100-113e-11ea-815e-59be77709cbc.png)

Also I'm a bit confused by the on site map. According to it, Sapphire City and its continent is outside of the world. But they show up when you zoom in. In previous version there was just end lands this far out though.

If applicable, please also upload your latest.log (as a file or using pastebin) so we can further investigate.

**Comment by NLBlackEagle** [comment]
Hello Craft90,

I tought I had fixed this in 1.62 as I added in the old beaches, apperantly there are some remaining though. I will add this to the 1.63 to do list and release a version ASAP ( Maybe as soon as tomorrow )

As for the https://dregora/maps/ I have updated this today, it could be that your web browser has cached the page. Press CTRL + F5 to refresh the page, the new icons should be visible after. This is how it should look:
![afbeelding](https://user-images.githubusercontent.com/4073584/69744680-ef625700-1140-11ea-9c0a-c47d249f4bc3.png)

Thanks for the bug report!

[Added to 1.63]

**Comment by craft90** [comment]
I didn't have this issue in the old version as far as I can remember. Sure there was a little bit of an incline up to land but not this sharp and tall V shape. More like a bulge raising from sea to land.

Thanks! The suggestion fixed the map issue. I didn't see any Sapphire City spawning where it was supposed to spawn though. But that might be a seed issue. I did find a lone ship below the ghostly plains in the sea where Sapphire City should have been. (also stranded pirates ships in the plains. Witch ships. Also one down in the caves below (i used Spectator mode)) Across there sea there was a partially formed tribal village on the In-Construction island (continent?) too. Partially as in a market spawned on top and a wall along the coastline. I imagine that's due to that part of the map being incomplete.

**Comment by NLBlackEagle** [comment]
I just fixed up the beach biomes for the "to be released" 1.63 update. The information on sapphire city was also quite handy as I've found out it didnt spawned while it should spawn. I have fixed that for atleast the seed Dregora. 

I will be fixing some minor issues which you can see under the 1.63 swimlane at [http://public.dregora.com](http://public.dregora.com) I will release this version as soon as I am done fixing the issues I found while fixing the beaches ( There are not a lot so pretty soon! )

**Comment by NLBlackEagle** [comment]
Here's a small teaser for upcoming minor changes :) This is the fantasy forest, remade:

I have also fixed the coordinates for the maps on dregora.com ( CTRL+F5 should do the trick if you cant find the coordinates bottom left )

![afbeelding](https://user-images.githubusercontent.com/4073584/70006801-b118cd80-156e-11ea-8585-36c17a6882bb.png)

**Comment by craft90** [comment]
I'm really happy to hear that you managed to fix the issue. Looking forward to the next update. I must admit I'm not too sure how to use seeds with OTG. Every time I try I end up in the middle of a never ending ocean. So I've been leaving is blank since.
