### ISSUE TITLE
Excessive windmill spawning

### ISSUE THREAD

**Issue by SamB440** [NLBlackEagle/Dregora#25]
#### Dregora Mod/Plugin
- [ ] OTG Mod for Forge
- [x] OTG Plugin for Spigot

#### Dregora Version
- [x] V1.62
- [ ] V1.61
- [ ] V1.60

#### Seed and Location
1916232494 -2943 137 637
#### Description
Windmills are spawning in very large amounts:
![image](https://user-images.githubusercontent.com/11319274/81504578-06a59300-92e2-11ea-851e-c65ac4282c1f.png)

**Comment by NLBlackEagle** [comment]
Fixed in latest builds.
