### ISSUE TITLE
[question] Is there a way to modify loot tables yet?

### ISSUE THREAD

**Issue by xEnigma04** [NLBlackEagle/Dregora#27]
I am making a mod pack with this and was wondering if there was a way to edit loot tables to structures generated by this mod. If so how

**Comment by NLBlackEagle** [comment]
Hello XEnigma04,

The loot tables currently are deeply buried in the mod files and hardcoded. It is possible to edit the source files which are in .NBT format. In future updates i plan to clean these all up and move them to a parent folder so it's easier for both me and others to globally edit the nbt files.

So while the answer is yes, it is probably not what you expected it to be. Let me know if you are up to editing all the loot tables by introducing your own ones. If you plan to append some items it's actually even pretty easy.

**Comment by NLBlackEagle** [comment]
If you are still interested, in future updates after the cleanup I will make loottables easier to access. Feel free to hit me up if you want to know more.
