### ISSUE TITLE
falling through the void

### ISSUE THREAD

**Issue by matthewjessee16** [NLBlackEagle/Dregora#29]
[latest.log](https://github.com/NLBlackEagle/Dregora/files/7230374/latest.log)
![Desktop Screenshot 2021 09 25 - 16 51 48 68](https://user-images.githubusercontent.com/58116173/134786350-986ceb8e-330b-4516-88a7-7687036b6baf.png)

i dont know why this is happening

**Comment by NLBlackEagle** [comment]
Does this still happen or was this resolved? I take it was another mod causing it? Feel free to reopen if it still happens.
