### ISSUE TITLE
Message after disabling welcome gives wrong command to re-enable welcome

### ISSUE THREAD

**Issue by bakerfugu** [NLBlackEagle/Dregora#3]
Super minor issue, but after disabling the welcome message with `/cr-confirm` the message response states that `/cr-unconfirmed` will re-enable the message when the correct command to re-enable is `/cr-unconfirm`.

![image](https://user-images.githubusercontent.com/7607483/27248173-ca1367fc-52b4-11e7-8bda-0834da004922.png)

**Comment by NLBlackEagle** [comment]
Issue-fix Scheduled for next Denizen Build

**Comment by NLBlackEagle** [comment]
Issue-Fix released for Build 1.60 ( Latest Denizen Package )
/cr-unconfirmed changed into /cr-unconfirm
