### ISSUE TITLE
Lag when crossing chunks

### ISSUE THREAD

**Issue by SzczurekYT** [NLBlackEagle/Dregora#30]
#### Dregora Mod/Plugin
- [ x ] OTG Mod for Forge

#### Dregora Version
- [ x ] V1.62

#### Seed and Location
Not applicable

#### Description
Two things to note:
1. Not sure if it's dregora fault or otg fault so I will report the issue on both.
2.  The issue occurs in normal non dregora worlds, any seed. Looks like in dregora worlds it's fine.
I'm testing custom self made modpack and found an issue.
The thing is that when I cross chunks there is pretty big fps drop \ lag spike.
Removing the mod fixed the issue.
As I said this is probably more otg issue than dregora but for sure I report it also here.

**Comment by SamB440** [comment]
This is a vanilla issue with lighting

**Comment by NLBlackEagle** [comment]
Was the issue resolved? Or do you know more about it?  Not a lot I could do I think but I did change some lightning settings with the latest update.

**Comment by SzczurekYT** [comment]
I'm gonna close this, as no one else  reported this problem, and now I don't have a way to check if this is still a problem. (Probably not)
