### ISSUE TITLE
[1.16.5] Fog is 100% in dregora:dregora_rfvolcanicplateau so you can't see anything at all.

### ISSUE THREAD

**Issue by ProsperCraft** [NLBlackEagle/Dregora#32]
#### Dregora Mod/Plugin
▶️Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []◀️
- [ X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️
Dregora-1.71

#### Seed and Location
▶️Specify the seed you are using and the location of the issue if applicable◀️
5190194206154131433
-1247 80 1245

#### Description
This
![image](https://user-images.githubusercontent.com/4427684/144076408-2f7336c2-80e6-4564-b2d9-2f7ab95968ae.png)
Becomes this after stepping forward one block.
![image](https://user-images.githubusercontent.com/4427684/144076507-ca51b422-1a57-4626-b3ca-f13c8a7f5e18.png)

**Comment by NLBlackEagle** [comment]
Thanks for reporting! Fixed with latest build 1.73

**Comment by ProsperCraft** [comment]
Not fixed, do we need to let configs regen?

**Comment by NLBlackEagle** [comment]
Yeah, that is probably the case here. Delete the the folder dregora in /config/openterraingenerator/presets/
