### ISSUE TITLE
[1.16.5 issue] [Mod Conflict?] Dregora generated spawn point map area is sunken in.

### ISSUE THREAD

**Issue by wasdspace** [NLBlackEagle/Dregora#34]
#### Dregora Mod/Plugin
▶️Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []◀️
- Forge: 36.2.19
- OTG: 0.1.6
- JDK: 16.0.2+7

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️
- V1.73

#### Description
▶️What is happening? - Dregora generated spawnpoint map area is sunken in. So laggy.

![2021-12-07_23 44 12](https://user-images.githubusercontent.com/85009668/145062165-67f62871-ae6c-4281-98d2-b2e26875b945.png)
![2021-12-07_23 44 19](https://user-images.githubusercontent.com/85009668/145062189-ec513038-f25a-4054-9fb2-d6ee10ca9abe.png)
![2021-12-07_23 44 25](https://user-images.githubusercontent.com/85009668/145062208-7f084335-056f-489c-8c97-585f19a386b3.png)

One more thing, the various biomes are not named.

Finally, I will perform mod variance tests sometime and tell you the result.

**Comment by NLBlackEagle** [comment]
Thanks for reporting these issues. I'm cooking up a solution as of this very moment and hopefully at least the biomes should be fixed. The big hole in the ground is something that will require some more looking into and I may not be able to fix it but re-generating dregora again should give you a fair chance of actually generating the structure there as it should generate.

I'm hoping I will have a fix uploaded between one and 3 hours.

**Comment by wasdspace** [comment]
Thanks for the quick reply!
My English sucks so most likely I didn't express my point clearly. I tried to create the world twice and besides the different structures around it, the large circular area around the spawnpoint (as shown in the third picture) seems to sink, that is it is below sea level. It's as if the lake island sank, and then the water around it flowed downward causing a delay. The rest of the world seems normal.
The structures on this area are floating in the air (or where they are supposed to be).

**Comment by NLBlackEagle** [comment]
I've just finished fixing some compatibility issues and will upload a new build pretty soon. As for the spawn, the hole is supposed to be there but it shouldn't be empty. It should look like this:

![afbeelding](https://user-images.githubusercontent.com/4073584/145083984-66a02e91-42df-4d47-a249-4b5e688bf391.png)

Take a look in about 10 minutes and the new build should be uploaded.

**Comment by wasdspace** [comment]
Thank you! 
I'm sorry I didn't go into detail about your mod at first, I thought this spawnpoint structure needs extra configuration. I'll definitely try it out first thing tomorrow, it's 3am in my time zone now and I had to go to bed. 
Thanks again!

**Comment by NLBlackEagle** [comment]
Uploaded & Approved! If you would test this version and please share your findings here (Fixed or not)
Oh and yeah, no rush tomorrow is good 👍 

Here's the new version: https://www.curseforge.com/minecraft/mc-mods/dregora/files/3554025

**Comment by wasdspace** [comment]
I'm back from testing! Worked perfectly!
But displaying biome names like that at the bottom of FTBC doesn't seem very aesthetically pleasing, it's easy to name them?
Also I noticed that you are working on compatibility with biome overhaul mods, if it's done Dregora will really be a must have mod for me, im always waiting for that ; )
Nice work!

**Comment by NLBlackEagle** [comment]
Could you make a screenshot of this? "But displaying biome names like that at the bottom of FTBC doesn't seem very aesthetically pleasing, it's easy to name them" I'm not sure what you mean but Dregora shouldnt have any of those kind of naming credits.

Other then that, nice to hear everything works now 👍 :)

**Comment by wasdspace** [comment]
You see a small map(from FTBC mod) in the upper right corner of the first and second pictures, and the line "biome.otg......" below it should show the exact name of the biome such as "Rflake Center" or "Dregora Rflake Center".
Do you have any good ideas about this?
