### ISSUE TITLE
1.12.2problem

### ISSUE THREAD

**Issue by 623667595** [NLBlackEagle/Dregora#37]
After the update of dregora-1.12.2-v1.9, buildings will not be generated in ancient wars, and many mod buildings and creatures will not be generated, such as magic baby. There is no problem with the generation of the old version, but it will not work after the update

**Comment by NLBlackEagle** [comment]
Ill have a look into this, what mod was it? Ancient Warefare?

**Comment by NLBlackEagle** [comment]
Closed due to lack of response / more information
