### ISSUE TITLE
[1.12.2] Alot of items are on the ground

### ISSUE THREAD

**Issue by quentin452** [NLBlackEagle/Dregora#38]
#### Dregora Mod/Plugin

- [x] OTG Mod for Forge X
- [ ] OTG Plugin for Spigot

#### Dregora Version

- [ ] V1.74
- [ ] V1.66
- [ ] V1.65
- [ ] V1.64
- [x] V1.9 Content Update Phase 1 X

#### Seed and Location

seed : 8874236358285262575
location : -1057 78 -5846

#### Description
Alot of items are on the ground 
https://prnt.sc/hpS5hexbWgrO
https://prnt.sc/QSjRR4pLH8Hl

**Comment by NLBlackEagle** [comment]
Thanks for reporting! Will be fixed next update

**Comment by quentin452** [comment]
thx

**Comment by NLBlackEagle** [comment]
Fixed for Dregora V2.0 (upcoming update)
- removed Sand Ore resource overwriting grassblocks with tallgrass on top causing the grass to break
