### ISSUE TITLE
Make modpack avalible in other platform

### ISSUE THREAD

**Issue by YUNGHOD** [NLBlackEagle/Dregora#42]
i cant search dregora in curseforge, neither in app nor FTB app. Also since curseforge is turning unfriendly towards 3rd party minecraft launcher, i suggest hosting Dregora in other place such as modrinth and AT launcher

**Comment by NLBlackEagle** [comment]
What 3rd party launcher are you using if I may ask?

**Comment by SamB440** [comment]
Potentially Dregora has third party download requests turned off in its CurseForge settings @NLBlackEagle. Otherwise unsure why it would not appear.

**Comment by NLBlackEagle** [comment]
Good point, I've just checked though and had already turned it on @SamB440

**Comment by NLBlackEagle** [comment]
Was unable to replicate the issue. Feel free to re-open with new information provided on how to replicate the issue
