### ISSUE TITLE
Dregora_CorruptedBloodForest not spawning Lycanite or Vanilla mobs

### ISSUE THREAD

**Issue by ddmjr22** [NLBlackEagle/Dregora#44]
#### Dregora Mod/Plugin
▶️Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []◀️
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️
- [x] Dregora+RL-1.4
- [ ] V1.9
- [ ] V1.74
- [ ] V1.66
- [ ] V1.65
- [ ] V1.64

#### Seed and Location
▶️ 5539672473947374258   /tp 17629 93 -15889   Dregora_CorruptedBloodForest◀️

#### Description
▶️Dregora_CorruptedBloodForest seems to not (or at least very rarely) spawn lycanite & vanilla creatures. It still spawns mobs that come from generated structures like icenfire dragons and pixes though. 

*Be advised that the pictures shown are different from the seed and location I've given due to me deleting the world before grabbing the previous location. But even in the new world the same result persisted. 

1st picture shows overhead view of bugged biome with no mobs at night.

![2023-05-02_17 07 46](https://user-images.githubusercontent.com/66555833/235800518-4cf5b0fd-d68c-4093-bebc-17d6d50b9e46.png)

2nd pictures shows all mobs spawning outside of bugged biome in neighboring biome (Dregora_DrySavanna)

![2023-05-02_17 15 08](https://user-images.githubusercontent.com/66555833/235800558-14b1280c-a762-4f7e-8d44-0e3c918adb53.png)

**Comment by NLBlackEagle** [comment]
Fixed for v1.6, you can download it here: https://legacy.curseforge.com/minecraft/mc-mods/dregora-rl
