### ISSUE TITLE
[Issue] Weird error on initialization, reproduced on different systems.

### ISSUE THREAD

**Issue by dyngari** [NLBlackEagle/Dregora#45]
Trying to play Dregora with my two friends. All three of us did a fresh install of RLCraft through curseforge following the Discord pinned instructions. Two of us are getting this error when we try and join the server, but one of us joins fine. 
![image](https://github.com/NLBlackEagle/Dregora/assets/41542958/6cb330e6-8144-4776-b41f-5c8d3003843b)

**Comment by NLBlackEagle** [comment]
Did you also installed the configs as provided with the same pins?

**Comment by dyngari** [comment]
yes

**Comment by NLBlackEagle** [comment]
Could you try replacing /minecraft/scripts/Dregora.zs with "Dregora.zs" file within the following .zip file:
[Dregora.zip](https://github.com/NLBlackEagle/Dregora/files/11569781/Dregora.zip)

I've removed the offending recipe and replaced it by a valid one, I can't guarantee it'll work but it may do.

Oh and I nearly forgot to thank you for reporting this issue as I'm grateful you did so!

**Comment by NLBlackEagle** [comment]
It seems there is some odd issue with adding in the fix (duplicate uses) Ill get to fixing it and upload a new one once it's fixed.

**Comment by NLBlackEagle** [comment]
Could you give me your latest.log and had you installed BOP + BOP Dynamictrees?

**Comment by NLBlackEagle** [comment]
Fixed for V1.8
