### ISSUE TITLE
Dregora RL Crash

### ISSUE THREAD

**Issue by 99descending** [NLBlackEagle/Dregora#47]
#### Dregora Mod/Plugin
▶️Please specify if it's about Forge Mod or Spigot server Plugin placing "x" into []◀️
- [x] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [x] V1.7 RLCraft
- [ ] V1.9
- [ ] V1.74
- [ ] V1.66
- [ ] V1.65
- [ ] V1.64

#### Seed and Location
▶️Specify the seed you are using and the location of the issue if applicable (Use /otg biome)◀️

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue. Ideally with pictures.
Minecraft crashes a few seconds after pressing play, I followed the Dregora RL install guide on youtube, with a fresh RLCraft install.
I attached the log file and I'll also attach a screenshot of the crash pop-up thingy in the minecraft launcher. I'm sorry if I might have missed something.
[latest.log](https://github.com/NLBlackEagle/Dregora/files/11885961/latest.log)
![Screenshot 2023-06-27 211722](https://github.com/NLBlackEagle/Dregora/assets/64549274/e9f52f2f-b23f-4063-91b7-8a9b408121bf)

**Comment by NLBlackEagle** [comment]
Was the error resolved? (As you closed it, and if so how did you resolve it?)

**Comment by NLBlackEagle** [comment]
(For anyone else bumping into this issue): Tickprofiler & Libloader.jar caused the crash. deleting those solved the issue.
