### ISSUE TITLE
Random tree tower?

### ISSUE THREAD

**Issue by Edwards07256** [NLBlackEagle/Dregora#5]
![screenshot 13](https://user-images.githubusercontent.com/38186043/39623117-3734f39e-4f5a-11e8-9fb4-ac0ae92b060a.png)

Apologize for the really small window, but I came across this "bug" There were at least 4 of these structures in the area.

**Comment by NLBlackEagle** [comment]
Could you give me a location of where this is happening? I personally suspect the new colission and ontopof features from OTG where at work here and will look in to them soon, thanks for posting the issue :)

Issue has been found and is being worked on

**Comment by Giskard13** [comment]
I found a few of these in ForestOnlyPine, and it appeared to be coming from mineshafts

**Comment by NLBlackEagle** [comment]
The issue has been resolved for version 1.1 on curseforge. The wood tower has been fixed. There are still floating blocks at 256 though, I will need to do some extended experimenting to fix as my earlier 3 hour attempt failed to do so.

**Comment by NLBlackEagle** [comment]
Fixed for upcoming beta build V1.2

Thanks again ( a lot! ) For posting this issue
