### ISSUE TITLE
Random dirt / gravel spawning in village keep bo3

### ISSUE THREAD

**Issue by SamB440** [NLBlackEagle/Dregora#7]
In the village / town keep bo3 random dirt and gravel will spawn in it.

![2018-05-04_16 41 39](https://user-images.githubusercontent.com/11319274/39637177-26663856-4fba-11e8-9652-5eb8159f1fd5.png)

**Comment by NLBlackEagle** [comment]
Fixed as of v1.62 by pushing the customstructure() below the ore generation in the queue.
